version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "*" # Ignore major updates
        update-types: [ "version-update:semver-major" ]
